### ISSUE TITLE
Can you build a prebuild version for electron9

### ISSUE THREAD

**Issue by scofieldpeng** [thiagoelg/node-printer#15] opened 2020-08-12 06:55 UTC
Hi, i see you create a pr to source repo for electron9 and node 12, can you create a tag for your own repo for prebuild release? Thanks a million:-)

**Comment by thiagoelg** [comment] 2020-08-14 03:38
Hello!
We use [prebuild](https://github.com/prebuild/prebuild) to generate builds and releases, but unfortunately it hasn't been updated to build for Electron 9 (it kind of builds, but it targets v80 instead of v83, for some reason).

You can build it locally if you want, you can see the commands on the scripts here ([buildElectronLinux.sh](https://github.com/thiagoelg/node-printer/blob/master/tools/buildElectronLinux.sh)) for Linux, and here ([buildElectronWindows.ps1](https://github.com/thiagoelg/node-printer/blob/master/tools/buildElectronWindows.ps1)) for Windows. 
Just be sure to have `node-pre-gyp` and python installed (on Linux you may need to install libcups2-dev via apt or whatever package manager you use).

**Comment by TimoKunze** [comment] 2020-08-25 09:17
I can use node-printer with electron 9.2.1 if I run `npm upgrade node-abi --depth=10` followed by `electron-rebuild`.

**Comment by TimoKunze** [comment] 2020-08-29 22:14
> I can use node-printer with electron 9.2.1 if I run `npm upgrade node-abi --depth=10` followed by `electron-rebuild`.

Hmm, the only problem I noticed is that on some machines this for some reason builds a 32 bit node module (node_printer.node) instead of a 64 bit one. I have not yet found out why this happens.

**Comment by falahati** [comment] 2020-11-14 19:39
@TimoKunze solution works great with the latest version of the Electron at the time (10.1.5), but since I was using the library in the renderer process, I had to set the `app.allowRendererProcessReuse` to `false`. Apparently, this should be fixed here. Meanwhile, I don't really have more than one window/renderer process for my app and this isn't an issue. Unless they decide to remove the flag at some time in the future.

**Comment by TimoKunze** [comment] 2020-11-20 13:11
@falahati Electron 11 seems to be the last release that supports such libraries. I hope this library gets updated until then. I don't know how to do it, otherwise I would try to create a patch.

**Comment by TimoKunze** [comment] 2021-01-08 17:51
@falahati Have you already tested this package with Electron 11? Does it still work?

**Comment by falahati** [comment] 2021-01-08 17:53
I am still on 10 so I don't really know.

**Comment by TimoKunze** [comment] 2021-02-12 14:50
At least for my use case it still works in Electron 11. However, I have other issues with Electron 11, so I'll go back to 10.
I also did try with Electron 12 Beta 24 and it still works. But it might be because I don't use the library from the renderer process.

**Comment by jyooi** [comment] 2021-03-09 03:43
thanks million from here, finally I can run my electron rebuild on my upgraded electron here with this node-printer library.

electron 8.2.5 
nodejs: v12.13.1

**Comment by thiagoelg** [comment] 2021-06-08 23:56
Hi everyone!
I finally got some time to work a little in this library, and based on the work of @ivannkf I managed to make prebuilds go up to Electron 13 and Node 16! You can check them on the [0.5.5 release](https://github.com/thiagoelg/node-printer/releases/tag/v0.5.5).

I didn't get to test all these versions, so I'm not sure they're working as intended, but let me know if you find any problems.

**Closed** 2021-06-17 23:58 UTC
